ABP_DB_VERSION = "v1"

ABP_ADDON_NAME = "Key Bind Profiles"
ABP_DOWNLOAD_LINK = "https://mods.curse.com/addons/wow/action-bar-profiles"

ABP_MAX_ACTION_BUTTONS = 120
ABP_DEFAULT_PAPERDOLL_NUM_TABS = 3

ABP_PICKUP_RETRY_COUNT = 5
ABP_PICKUP_RETRY_INTERVAL = 0.1

ABP_EMPTY_ICON_TEXTURE_ID = 134400
ABP_RANDOM_MOUNT_SPELL_ID = 150544

ABP_TOME_OF_CLEAR_MIND_SPELL_ID = 227563
ABP_TOME_OF_TRANQUIL_MIND_SPELL_ID = 227041
ABP_DUNGEON_PREPARE_SPELL_ID = 228128
