name: Create Release ZIP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release ZIP
        run: |
          version="1.1.2"
          addon_dir="KeyBindProfiles"
          find "$addon_dir" -type f -not -name '.gitignore' -not -name 'build-release-zip.yml' | xargs zip -r "KeyBindProfiles-$version-release.zip" $addon_dir --exclude "$addon_dir/.github/workflows/*"
        working-directory: ${{ github.workspace }}

      - name: Upload Release ZIP
        uses: actions/upload-artifact@v2
        with:
          name: release-zip
          path: "KeyBindProfiles-$version-release.zip"
