name: Create Release ZIP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release ZIP
        run: |
          version="1.1.2"
          addon_dir="KeyBindProfiles"
          zip -r "KeyBindProfiles-$version-release.zip" $addon_dir
        working-directory: ${{ github.workspace }}

      - name: Upload Release ZIP
        uses: actions/upload-artifact@v2
        with:
          name: release-zip
          path: "KeyBindProfiles-$version-release.zip"
