name: Create Release and Upload ZIP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: 1.1.2  # Define the version as an environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release ZIP
        run: |
          addon_dir="KeyBindProfiles"
          zip -r "KeyBindProfiles-$VERSION-release.zip" $addon_dir
        working-directory: ${{ github.workspace }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: "KeyBindProfiles-$VERSION-release.zip"
          tag_name: ${{ format('v{0}-release', env.VERSION) }}
          release_name: KeyBindProfiles-$VERSION
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

